import { Injectable, InternalServerErrorException } from '@nestjs/common';
import { randomBytes, createCipheriv, createDecipheriv } from 'crypto';

@Injectable()
export class CryptoService {
  private readonly algorithm = 'aes-256-gcm';

  /**
   * Encrypts plain text using AES-256-GCM.
   * Returns a string in format: iv:authTag:encryptedData (all hex encoded)
   */
  encrypt(data: string, key: Buffer): string {
    // SECURITY MEANING: We use a truly random Initialization Vector (IV) for every encryption.
    // In GCM mode, the IV should ideally be 12 bytes (96 bits) for maximum efficiency and security as recommended by NIST.
    // Reusing an IV with the same key in GCM is catastrophic, as it compromises the confidentiality and authenticity of the data.
    const iv = randomBytes(12);

    const cipher = createCipheriv(this.algorithm, key, iv);
    
    let encrypted = cipher.update(data, 'utf8', 'hex');
    encrypted += cipher.final('hex');

    // SECURITY MEANING: The AuthTag is a MAC (Message Authentication Code) generated by the GCM algorithm.
    // It guarantees both data integrity (that the data hasn't been changed) and authenticity (that it was encrypted with the correct key).
    // During decryption, if the AuthTag doesn't match the ciphertext, it will throw an error and we know the data was tampered with.
    const authTag = cipher.getAuthTag().toString('hex');

    return `${iv.toString('hex')}:${authTag}:${encrypted}`;
  }

  /**
   * Decrypts encrypted string format (iv:authTag:encryptedData) using AES-256-GCM.
   */
  decrypt(encryptedString: string, key: Buffer): string {
    const parts = encryptedString.split(':');
    
    if (parts.length !== 3) {
      throw new InternalServerErrorException('Invalid encrypted data format');
    }

    const [ivHex, authTagHex, encryptedHex] = parts;

    const iv = Buffer.from(ivHex, 'hex');
    const authTag = Buffer.from(authTagHex, 'hex');

    try {
      const decipher = createDecipheriv(this.algorithm, key, iv);
      decipher.setAuthTag(authTag); // Crucial step for GCM to verify integrity

      let decrypted = decipher.update(encryptedHex, 'hex', 'utf8');
      decrypted += decipher.final('utf8');

      return decrypted;
    } catch (error) {
      // SECURITY MEANING: If the `final()` call fails, it generally means the tag didn't match.
      // This indicates the data was modified, or an incorrect key was used.
      throw new InternalServerErrorException('Failed to decrypt data: Authentication tag validation failed or incorrect key');
    }
  }
}
